# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{compojure}
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["gabrielg"]
  s.date = %q{2009-11-22}
  s.description = %q{The Compojure web framework}
  s.email = %q{gabriel@javagems.org}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "compojure.gemspec",
     "lib/compojure.clj",
     "lib/compojure/control.clj",
     "lib/compojure/crypto.clj",
     "lib/compojure/encodings.clj",
     "lib/compojure/html.clj",
     "lib/compojure/html/form_helpers.clj",
     "lib/compojure/html/gen.clj",
     "lib/compojure/html/page_helpers.clj",
     "lib/compojure/http.clj",
     "lib/compojure/http/helpers.clj",
     "lib/compojure/http/middleware.clj",
     "lib/compojure/http/multipart.clj",
     "lib/compojure/http/request.clj",
     "lib/compojure/http/response.clj",
     "lib/compojure/http/routes.clj",
     "lib/compojure/http/servlet.clj",
     "lib/compojure/http/session.clj",
     "lib/compojure/map_utils.clj",
     "lib/compojure/ns_utils.clj",
     "lib/compojure/server/common.clj",
     "lib/compojure/server/grizzly.clj",
     "lib/compojure/server/jetty.clj",
     "lib/compojure/str_utils.clj",
     "lib/compojure/validation.clj",
     "lib/compojure/validation/predicates.clj",
     "test/compojure/crypto.clj",
     "test/compojure/html/form_helpers.clj",
     "test/compojure/html/gen.clj",
     "test/compojure/html/page_helpers.clj",
     "test/compojure/http/helpers.clj",
     "test/compojure/http/middleware.clj",
     "test/compojure/http/request.clj",
     "test/compojure/http/response.clj",
     "test/compojure/http/routes.clj",
     "test/compojure/http/session.clj",
     "test/compojure/str_utils.clj",
     "test/compojure/validation.clj",
     "test/helpers.clj",
     "test/run.clj"
  ]
  s.homepage = %q{http://github.com/javagems/compojure}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A JavaGem packaged version of Compojure}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<clojure>, [">= 0"])
      s.add_runtime_dependency(%q<clojure-contrib>, [">= 0"])
      s.add_runtime_dependency(%q<jetty>, [">= 0"])
      s.add_runtime_dependency(%q<jetty-util>, [">= 0"])
      s.add_runtime_dependency(%q<commons-fileupload>, [">= 0"])
      s.add_runtime_dependency(%q<commons-codec>, [">= 0"])
      s.add_runtime_dependency(%q<commons-io>, [">= 0"])
      s.add_runtime_dependency(%q<servlet-api>, [">= 0"])
    else
      s.add_dependency(%q<clojure>, [">= 0"])
      s.add_dependency(%q<clojure-contrib>, [">= 0"])
      s.add_dependency(%q<jetty>, [">= 0"])
      s.add_dependency(%q<jetty-util>, [">= 0"])
      s.add_dependency(%q<commons-fileupload>, [">= 0"])
      s.add_dependency(%q<commons-codec>, [">= 0"])
      s.add_dependency(%q<commons-io>, [">= 0"])
      s.add_dependency(%q<servlet-api>, [">= 0"])
    end
  else
    s.add_dependency(%q<clojure>, [">= 0"])
    s.add_dependency(%q<clojure-contrib>, [">= 0"])
    s.add_dependency(%q<jetty>, [">= 0"])
    s.add_dependency(%q<jetty-util>, [">= 0"])
    s.add_dependency(%q<commons-fileupload>, [">= 0"])
    s.add_dependency(%q<commons-codec>, [">= 0"])
    s.add_dependency(%q<commons-io>, [">= 0"])
    s.add_dependency(%q<servlet-api>, [">= 0"])
  end
end

